[🚧 WIP] Install flutter in publishing step
breez/breez-sdk-flutter pull request #8
Opened 2024-02-17 13:17 UTC by cnixbtc

[Previous attempts to publish to pub.dev](https://github.com/breez/breez-sdk-flutter/actions/runs/7913697862) failed due to Flutter not being installed on the runner.

2024-02-17 15:02 UTC, erdemyerebasmaz requested changes
LGTM

Have one comment regarding having a fixed Flutter SDK version.

2024-02-17 15:05 UTC, cnixbtc commented on .github/workflows/publish.yml
> +          version: 3.19.0
Ah yea good point thx!

2024-02-19 09:14 UTC, JssDWt approved these changes
LGTM

2024-02-19 09:20 UTC, roeierez approved these changes
LGTM

2024-02-19 09:29 UTC, merged